// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9u7AFQJWws2ksJS5HCvEvMULx6-6FS0',
    appId: '1:236224889254:web:97a67c4cced027ed560f67',
    messagingSenderId: '236224889254',
    projectId: 'master-calculator-51684',
    authDomain: 'master-calculator-51684.firebaseapp.com',
    storageBucket: 'master-calculator-51684.firebasestorage.app',
    measurementId: 'G-NM64QVRCTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVpNLdAt5hkEi_CYML0FCAzIEwpvh7MPQ',
    appId: '1:236224889254:android:0deb1f6a9963a9e5560f67',
    messagingSenderId: '236224889254',
    projectId: 'master-calculator-51684',
    storageBucket: 'master-calculator-51684.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbFIiC_f-1qeYC3FZBFUtpiGxDyyQDHAA',
    appId: '1:236224889254:ios:e5b077d1fea3ec44560f67',
    messagingSenderId: '236224889254',
    projectId: 'master-calculator-51684',
    storageBucket: 'master-calculator-51684.firebasestorage.app',
    iosClientId: '236224889254-p8e9j9u26ri9bdd569412htcteapb9jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbFIiC_f-1qeYC3FZBFUtpiGxDyyQDHAA',
    appId: '1:236224889254:ios:e5b077d1fea3ec44560f67',
    messagingSenderId: '236224889254',
    projectId: 'master-calculator-51684',
    storageBucket: 'master-calculator-51684.firebasestorage.app',
    iosClientId: '236224889254-p8e9j9u26ri9bdd569412htcteapb9jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9u7AFQJWws2ksJS5HCvEvMULx6-6FS0',
    appId: '1:236224889254:web:26cb303697eccea9560f67',
    messagingSenderId: '236224889254',
    projectId: 'master-calculator-51684',
    authDomain: 'master-calculator-51684.firebaseapp.com',
    storageBucket: 'master-calculator-51684.firebasestorage.app',
    measurementId: 'G-VJ58GFBSH8',
  );
}
